[package]
name = "proc-maps"
version = "0.1.4"
authors = ["Julia Evans <julia@jvns.ca>", "Ben Frederickson <github@benfrederickson.com>"]
description = "Helper crate for getting virtual memory maps from processes"
license = "MIT"
homepage = "https://github.com/benfred/proc-maps"
repository = "https://github.com/benfred/proc-maps"

[dependencies]
libc = "0.2.34"
failure = "0.1.1"

[target.'cfg(target_os="macos")'.dependencies]
mach = "0.1.2"
libproc = "0.3.1"

[target.'cfg(target_os="linux")'.dependencies]
regex = "1.0"
lazy_static = "1.1"

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3", features = ["tlhelp32", "processthreadsapi", "handleapi", "impl-default", "dbghelp"]}
